---
# tasks file for tomcat
- include: ../../commons/tasks/jdk.yml

- name: install tomcat
  yum: name=tomcat state=present
  tags: install_tomcat

- name: enable tomcat
  service:
    name: tomcat
    state: started
    enabled: True
  tags: install_tomcat

# - name: check some path
#   file: path="{{ item }}" state=directory
#   with_items:
#     - "{{RSYNC_TMP_PATH}}"
#     - "{{PKG_OLD_VERSION_PATH}}"